[MLU] add mlu device for infer
PaddlePaddle/PaddleOCR pull request #10249
Opened 2023-06-27 02:58 UTC by PeiyuLau

add mlu device for infer

2023-07-10 05:57 UTC, onecatcn commented on tools/infer/utility.py
There is some discrepency between the codes for npu and mlu, please justify the difference.

2023-07-14 08:29 UTC, shiyutang requested changes

2023-07-14 08:29 UTC, shiyutang commented on tools/infer/utility.py
> +            config.enable_custom_device(dev_type)
The custom device should not be able to replace npu.

It seems you should add mlu device on top of the original code with another elif clause.

2023-07-18 06:06 UTC, shiyutang requested changes
any custom device is vague and should be replaced with mlu

2023-07-18 06:06 UTC, shiyutang commented on tools/infer/utility.py
> +        "--use_custom_device",
If you want to add mlu, I suppose it is better if this should is use_mlu.

2023-07-18 06:06 UTC, shiyutang commented on tools/infer/utility.py
> +            config.enable_custom_device(dev_type)
config.enable_custom_device("mlu")

2023-07-21 02:18 UTC, shiyutang approved these changes
LGTM

2023-07-21 02:22 UTC, merged