实现功能：当--savefile为true时，在--output下以当前图片名称后接“.txt”为文件名保存ocr推理结果
PaddlePaddle/PaddleOCR pull request #10612
Opened 2023-08-11 04:28 UTC by WilliamQf-AI

实现功能：当--savefile为true时，在--output下以当前图片名称后接“.txt”为文件名保存ocr推理结果，解决了如下issues：
https://github.com/PaddlePaddle/PaddleOCR/issues/10533

2023-08-11 04:30 UTC, WilliamQf-AI commented
实测使用如下命令行启动：--image_dir D:\imgs\15.png --use_angle_cls true --use_gpu false --savefile true
效果如图：
![image](https://github.com/PaddlePaddle/PaddleOCR/assets/40328063/98576d4c-db98-4123-96ce-eec80887c55f)

2023-08-14 02:13 UTC, shiyutang requested changes

2023-08-14 02:13 UTC, shiyutang commented on paddleocr.py
> +        args锛?
这里不太对，字符有问题？

2023-08-14 02:13 UTC, shiyutang commented on paddleocr.py
> +﻿# Copyright (c) 2020 PaddlePaddle Authors. All Rights Reserved.
这一行是什么修改呢？

2023-08-14 03:21 UTC, closed without merging