chore: add notes for docker gpu deploy PP-OCRv4
PaddlePaddle/PaddleOCR pull request #11390
Opened 2023-12-18 09:35 UTC by sheiy

2023-12-18 09:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/PaddleOCR?pullRequest=11390) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/PaddleOCR?pullRequest=11390) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/PaddleOCR?pullRequest=11390) it.</sub>

2023-12-21 02:35 UTC, shiyutang commented
请签署CLA后才可以合入。

2023-12-22 02:31 UTC, sheiy commented
@shiyutang 好了

2023-12-27 11:52 UTC, shiyutang requested changes

2023-12-27 11:52 UTC, shiyutang commented on deploy/docker/hubserving/gpu/Dockerfile
> +COPY {link} /PaddleOCR/inference/
ADD命令支持使用URL作为源路径，可以从网络下载文件并复制到容器中。
COPY不支持，需要还原到ADD

2023-12-28 09:37 UTC, sheiy commented on deploy/docker/hubserving/gpu/Dockerfile
> +COPY {link} /PaddleOCR/inference/
原来是这个考虑啊

2024-01-02 02:49 UTC, shiyutang approved these changes
LGTM

2024-01-02 02:49 UTC, merged