添加c++多线程并发，批量提升处理速度
PaddlePaddle/PaddleOCR pull request #949
Opened 2020-10-16 07:31 UTC by wangxiong101

1:修改main.cpp为main.cpp.bak，启用main_threadpool.bak;
2:run.sh传入目标图片文件夹

2020-10-16 07:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/PaddleOCR?pullRequest=949) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/PaddleOCR?pullRequest=949) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/PaddleOCR?pullRequest=949) it.</sub>

2020-10-16 07:53 UTC, BeyondYourself commented on deploy/cpp_infer/include/thread_pool.h
> +#ifndef THREAD_POOL_H
缺少licence吧

2020-10-16 09:01 UTC, littletomatodonkey requested changes

2020-10-16 09:01 UTC, littletomatodonkey commented on deploy/cpp_infer/src/main_threadpool.cpp.bak
> +std::vector<CRNNRecognizer> vecCRNNRec;
这块变量命名注意一下，和之前的代码统一一下吧，同时是否可以把全局变量挪到函数里面去呢？

2020-10-16 09:20 UTC, wangxiong101 commented on deploy/cpp_infer/include/thread_pool.h
> +//线程池,可以提交变参函数或拉姆达表达式的匿名函数执行,可以获取执行返回值
好的 我修改一下

2020-10-20 02:49 UTC, wangxiong101 commented on deploy/cpp_infer/src/main_threadpool.cpp.bak
> +std::vector<CRNNRecognizer> vecCRNNRec;
全局变量只能定义在函数外侧，或者重新在头文件声明，这样比较冗余

2020-10-20 02:50 UTC, wangxiong101 commented on deploy/cpp_infer/src/main_threadpool.cpp.bak
> +    std::cout<<"ERROR! no thread ID."<<std::endl;
新增了异常处理

2020-10-20 02:50 UTC, wangxiong101 commented on deploy/cpp_infer/src/main_threadpool.cpp.bak
> +  for(;i<vecID.size();i++)
已完成

2020-10-20 02:50 UTC, wangxiong101 commented on deploy/cpp_infer/src/main_threadpool.cpp.bak
> +void OCR_processing(cv::Mat srcmat)
ok

2020-10-20 02:51 UTC, wangxiong101 commented on deploy/cpp_infer/include/thread_pool.h
> +	std::vector<std::thread> pool;
在Windows虚拟机上没问题  实际真机后续会补充环境测试

2020-10-20 02:51 UTC, wangxiong101 commented on deploy/cpp_infer/include/thread_pool.h
> +{
ok

2020-11-02 06:27 UTC, wangxiong101 commented on deploy/cpp_infer/src/main_threadpool.cpp.bak
> +  std::string image_floder(argv[2]);
测试了下 glob支持对文件夹和文件自动支持

2022-05-17 08:59 UTC, closed without merging

2023-05-19 11:02 UTC, leizhu1989 commented
大佬，请问有线程池共享解释器，推理实现的吗